name: Tests

on:
  workflow_dispatch:

jobs:

  lint:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout full upstream repo
          uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name:
          run: |
            pip install aiohttp asyncio
        - name: Multiclient
          run: |
            python multiclient.py
